install.packages("pacman",lib="./local_package_library/3.5.1/")
install.packages("tidyverse",lib="./local_package_library/3.5.1/")
install.packages("dygraphs",lib="./local_package_library/3.5.1/")
install.packages("xlsx",lib="./local_package_library/3.5.1/")
install.packages("xts",lib="./local_package_library/3.5.1/")
install.packages("zoo",lib="./local_package_library/3.5.1/")
install.packages("hash",lib="./local_package_library/3.5.1/")
install.packages("htmlwidgets",lib="./local_package_library/3.5.1/")
install.packages("htmltools",lib="./local_package_library/3.5.1/")
install.packages("webshot",lib="./local_package_library/3.5.1/")
install.packages("foreach",lib="./local_package_library/3.5.1/")
install.packages("doParallel",lib="./local_package_library/3.5.1/")
install.packages("flexdashboard",lib="./local_package_library/3.5.1/")

